version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
      POSTGRES_DB: crypto_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  crypto-etl:
    build: .
    container_name: crypto_etl
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: crypto_db
      DB_USER: crypto_user
      DB_PASSWORD: crypto_pass
    restart: "no"

volumes:
  postgres_data:
